server:
  error:
    include-stacktrace: never


spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/teste?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver